import { useState } from "react";
import Head from "next/head";

import Logo from "components/atoms/logo";
import ArrowDown from "components/atoms/arrow-down";
import MainInfo from "components/molecules/MainInfo";

import styles from "styles/pages/Home.module.css";
import animationStyles from "styles/components/Animation.module.scss";

export default function Home() {
  const [showInfo, setShowInfo] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} ${
          showInfo ? animationStyles.body_animate : ""
        }`}
      >
        <div className="flex flex-col justify-center items-center">
          <Logo />
          {showInfo && (
            <MainInfo additionalStyles={showInfo && animationStyles.info} />
          )}
        </div>
        {!showInfo && (
          <div
            className="cursor-pointer absolute bottom-12"
            onClick={() => setShowInfo(!showInfo)}
          >
            <ArrowDown />
          </div>
        )}
      </main>
    </>
  );
}
